### ISSUE TITLE
Add import-map resolver

### ISSUE THREAD

**Issue by nestarz** [WebReflection/ucompress#7]
Thanks for this project !

I am doing a tool that build some files into a build folder and expose a import-map.json that is used to tell the browser to match some imports in the source code to the built files. See here for more information: https://github.com/nestarz/esdev

The thing is I can't use your tool with it because it doesn't use import maps like the browser do to resolve imports. 

Do you think it can be added easily ? Or if there is a workaround to it ?

**Comment by WebReflection** [comment]
AFAIK import maps aren't official yet, so starting supporting those already seems like a maintenance effort I won't have much time for.

However, the whole point of this project, together with [ucdn](https://github.com/WebReflection/ucdn-test#readme), is to not needing to care at all about import maps, meaning it does the mapping for you.

That being said, there is a CLI version and an export, so that you can use _ucompress_ as module and do the crawling yourself, including the parsing, but maybe I need to expose a flag that avoids resolving imports for you?

In that case you'll need to find those imports, either in HTML files (which is a bummer) or via a json file with such map, and do the resolving dance a part.

I'm not excluding to add support for this in the future, but as _ucompress_ already solved all my problems already, and I don't even need to generate import maps, it won't have high priority.

If you'd like to contribute though I'd be happy to consider this change 👋

**Comment by WebReflection** [comment]
P.S. on a second thought, I think _ucompress_ should bail out modules resolutions *if* an `*import-map.json` file is found in the root directory ... 'cause if you define that, it's *you* mapping resolutions, so that _ucompress_ might just do it's normal business there (crawl the folder and optimize without changing imports) ... what do you think?

This is much simpler than any other proposal to deal with import maps

**Comment by WebReflection** [comment]
Actually though ... on a third thought, if you don't have any `node_modules` in your source folder modules are simply left unresolved, so that kinda covers already your use case.

What I could do, is to avoid resolving modules that are not available in the source folder, but on any of their parent folders, so that you are in charge in that case.

This sounds like the best option to me, what do you think?

**Comment by nestarz** [comment]
Thanks for your interest,
Modules are present in an other directory named `web_modules`, it's where `webDependencies` should resolve, it's a spec made by [Snowpack](https://github.com/pikapkg/snowpack) and I copied this behavior in my package manager [Heritage](https://github.com/nestarz/heritage). Both Snowpack and Heritage expose an import-map.json so resolvers (the browser for example) could resolves modules.

The goal I think is to let the user add a list of import-map and use them by ucompress when using its resolve algorithm.

**Comment by WebReflection** [comment]
Uhm, basically you are saying if the import map file is passed along, ucompress should *not* change or resolve that import ... correct?

**Comment by nestarz** [comment]
Without resolving that import it would not be taken into account to be minimized right ? If so, I think I would like ucompress to resolve it *using* the import map. So the JS file can be minimized. I will try to propose this feature, I'm currently seeing how ucompress works and we'll try to PR.

**Comment by WebReflection** [comment]
Welcome to try, but I'd like to understand what's the goal ... I mean, if you serve an import map to the browser, such browser will use it, and if you defined such import map, you gotta have those files reachable through the browser, right? In such case, _ucompress_ crawls all files so that anything in there will be minified and copied at destination, and the import map, which is a json, will be there minified too, so everything will be optimized ... however, this is still the goal of this project:
  * do not care about source maps; work regularly with npm modules (currently must be reachable through the client but that might change soon), and call it a day

anything more complicated seems to be a job for third parts, which could use _ucompress_ regardless, as long as there is a way to disable module resolution, which seems to be desired if you really want to use import maps.

Things I don't like about import maps:
  * you need to define every possible dependency within modules you import too (this is solved in _ucompress_)
  * once you create an import map for every possible dependency, that file is massive, probably bigger than modules themselves once resolved

As it doesn't shine in practice, and as it's not available in any browser (AFAIK), are you sure this needs to be solved at all? 🤔

**Comment by nestarz** [comment]
To give you an example of what I failed to compress using ucompress, here a repo https://github.com/nestarz/ucompress-issue-importmap

It's all static, no command have to be launched to make it work in the browser, serve and see.

**Comment by WebReflection** [comment]
> It's all static, no command have to be launched to make it work in the browser

that means all you need is a flag to avoid resolving files, as I've previously mentioned, right?

**Comment by WebReflection** [comment]
in any case, you are using `.jsx` files in there, so you need a bundler/builder upfront. In such scenario, I'm not sure why you would need _ucompress_ at all, but having a flag to avoid resolving files seems the least I can offer in here, anything else feels like out of scope, as the `webDependencies` is not really standard, it's a 3rd parts tools idea, while _ucompress_ deals with standards, not `.ts`, nor `.jsx`, all things that need 3rd parts to work.

**Comment by WebReflection** [comment]
So, `v0.17` is out with a `--no-import` flag (or `noImport` option) to avoid automatic _ESM_ `import` resolution.

This should fix your current test case. For everything else I don't think _ucompress_ should do much, as the provided file will be in charge of resolving files already, which is not a _ucompress_ responsibility anymore, rather a developer choice to go in that direction.

If the file, as it must be by standards, is in the static build folder, that will be minified as json, like any other json file.

I hope this is enough 👋
